add state for tcp_wrappers

diff --git a/base/Linux/check_mk/custom/check_iostat-proc b/base/Linux/check_mk/custom/check_iostat-proc
--- a/base/Linux/check_mk/custom/check_iostat-proc
+++ b/base/Linux/check_mk/custom/check_iostat-proc
@@ -1,11 +1,11 @@
 #!/bin/bash
-BIN='/usr/sbin/iotop'
-which $BIN > /dev/null || $(echo "iotop Not Found !" && exit 3)
-
+if ! type iotop > /dev/null ;then
+  echo "iotop Not Found !" && exit 3
+fi
 PID=`pidof $1`
 if [ ! -z "$PID" ];then
-   DATA_READ=$( iotop -n 1 -b -p $PID -qqq | awk -F ' ' '{print $4}')
-   DATA_WRITE=$( iotop -n 1 -b -p $PID -qqq | awk -F ' ' '{print $6}')
+   DATA_READ=$(iotop -n 1 -b -p $PID -qqq | awk -F ' ' '{print $4}')
+   DATA_WRITE=$(iotop -n 1 -b -p $PID -qqq | awk -F ' ' '{print $6}')
    PERF_DATA="OK |data_read=${DATA_READ} B/s;;; data_write=${DATA_WRITE} B/s;;;"
    echo "$PERF_DATA" && exit 0
 else
