update

diff --git a/roles/cmk/agent/local/60/rmcping b/roles/cmk/agent/local/60/rmcping
--- a/roles/cmk/agent/local/60/rmcping
+++ b/roles/cmk/agent/local/60/rmcping
@@ -1,14 +1,17 @@
 #!/bin/bash
 if ! lsmod | grep ipmi_si -q;then
-    exit
+    echo "kernel module lost: ipmi_si"
+    exit 1
 fi
 
 if ! which ipmitool > /dev/null;then
-    exit
+    echo "command not found: ipmitool"
+    exit 1
 fi
 
 if ! type rmcpping > /dev/null;then
-    exit
+    echo "command not found: rmcpping"
+    exit 1
 fi
 
 IPMI_IP=$(ipmitool lan print |egrep '^IP Address *:' | cut -d ':' -f2 |  sed -n 's/\s*//gp')
